version: 2

defaults: &defaults
  working_directory: ~/project/glamor

  docker:
    - image: circleci/node:8-browsers
      environment:
        CHROME_BIN: "/usr/bin/google-chrome"

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

restore_cache: &restore_cache
  restore_cache:
    name: Restore node_modules cache
    keys:
      - deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - deps-{{ .Branch }}-
      - deps-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save node_modules cache
          key: depse-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  lint:
    <<: *defaults
    steps:
      - *restore_cache
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - *restore_cache
      - run:
          name: Test
          command: yarn test --coverage
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
